<?php

require_once dirname(__FILE__) . '/../../Cls/ReminderManagerFactory.php';


/**
 * Test class for ReminderManagerFactory.
 * Generated by PHPUnit on 2012-06-01 at 21:35:08.
 */
class ReminderManagerFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ReminderManagerFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = ReminderManagerFactory::CreateReminderManager();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testCreateReminderManager().
     */
    public function testCreateReminderManager() {
        // Remove the following lines when you implement this test.
        $this->assertInstanceOf('ReminderManager', $this->object);
    }

}

?>
